#!/usr/bin/env python
# -*- mode: python -*-

from __future__ import print_function, unicode_literals

import os
import platform
import sys

SEARCH_PATHS = [
    'bld/mach',
]

MACH_MODULES = [
    'bld/mach_commands.py'
]

def main(args):
    if sys.version_info[0] != 2 or sys.version_info[1] < 7:
        print('Python 2.7 or above (but not Python 3) is required to run mach.')
        print('You are running Python', platform.python_version())
        sys.exit(1)

    sys.path[0:0] = ["bld/mach"]
    import mach.main

    mach = mach.main.Mach(os.getcwd())
    mach.define_category('servo', 'Servo commands', 'Servo related functionalty', 80)

    for path in MACH_MODULES:
        mach.load_commands_from_file(path)

    mach.run(args[1:])

if __name__ == '__main__':
    main(sys.argv)
